name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - 'pom.xml'
      - '*.gradle'
      - 'src/**'
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./mvnw -B dependency:resolve-plugins dependency:resolve
      - run: ./mvnw
